package:
  name: python-cinderclient
  version: "1.1.2"

source:
  fn: python-cinderclient-1.1.2.tar.gz
  url: https://pypi.python.org/packages/source/p/python-cinderclient/python-cinderclient-1.1.2.tar.gz
  md5: c22e0e397ea1dc4d21862c07b9b949b1
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - cinder = cinderclient.shell:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - argparse # [py26]
    - prettytable <0.8,>=0.7
    - python-keystoneclient <1.4.0,>=1.2.0
    - "requests !=2.4.0,>=2.2.0"
    - simplejson >=2.2.0
    - babel >=1.3
    - six >=1.9.0

test:
  # Python imports
  imports:
    - cinderclient.client

  commands:
    - cinder --help

about:
  #home: The package home page
  license: Apache Software License
  summary: 'OpenStack Block Storage API Client Library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
